POST http://localhost:3001/api/account/register HTTP/1.1
content-type: application/json

{   "firstName":"nguyen",
    "lastName": "Son",
    "email": "nguyenthanhson162001@gmail.com",
    "password": "123"
}